/*
 * Copyright 2025 patryk3211
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
architectury.neoForge {
    platformPackage = "forge"
}

configurations {
    developmentNeoForge.extendsFrom common
}

dependencies {
    neoForge "net.neoforged:neoforge:${neoforge_version}"

    modImplementation("com.simibubi.create:create-${minecraft_version}:${create_forge_version}:slim") { transitive false }
    modImplementation("net.createmod.ponder:Ponder-NeoForge-${minecraft_version}:${ponder_forge_version}")
    modCompileOnly("dev.engine-room.flywheel:flywheel-neoforge-api-${minecraft_version}:${flywheel_forge_version}")
    modImplementation("com.tterrag.registrate:Registrate:${registrate_forge_version}")

    modImplementation "dev.architectury:architectury-neoforge:${architectury_api_version}"

    // Just Enough Items
    modCompileOnly "mezz.jei:jei-${minecraft_version}-forge-api:${jei_version}"

    // Roughly Enough Items - Forge
//    modCompileOnly "me.shedaniel:RoughlyEnoughItems-api-forge:$rei_version"

    // Create: The Factory Must Grow
    modCompileOnly "maven.modrinth:create-tfmg:1.2.0"

    compileOnly("io.github.llamalad7:mixinextras-common:${mixin_extras_version}")
    annotationProcessor(implementation(include("io.github.llamalad7:mixinextras-neoforge:${mixin_extras_version}")))

    shadowCommon(project(path: rootProject.path, configuration: "transformProductionNeoForge")) { transitive false }

    forgeRuntimeLibrary "org.ejml:ejml-core:0.44.0"
    forgeRuntimeLibrary "org.ejml:ejml-simple:0.44.0"
    forgeRuntimeLibrary "org.ejml:ejml-ddense:0.44.0"
    forgeRuntimeLibrary "org.ejml:ejml-dsparse:0.44.0"

    modLocalRuntime("dev.engine-room.flywheel:flywheel-neoforge-${minecraft_version}:${flywheel_forge_version}")
    modLocalRuntime("mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}")
//    modLocalRuntime("maven.modrinth:create-tfmg:1.2.0")
//    modLocalRuntime("me.shedaniel:RoughlyEnoughItems-forge:$rei_version")
}

loom {
    neoForge {
//        mixinConfigs("powergrid.mixins.json", "powergrid.client.mixins.json", "powergrid-forge.mixins.json")
    }

    runs {
        named("client") {
            vmArg("-enableassertions")
            vmArg("-Djava.library.path=" + rootProject.nativeLibDir)
        }

        create("data") {
            data()
            programArgs "--all", "--mod", "powergrid"
            programArgs "--output", file("src/main/generated").absolutePath
            programArgs "--existing", file("../src/main/resources").absolutePath
        }

        configureEach {
            programArg("-mixin.config=create.mixins.json")
            property "-Dmixin.debug.export=true"
            property "-Dmixin.env.remapRefMap=true"
            property "-Dmixin.env.refMapRemappingFile=${projectDir}/build/createSrgToMcp/output.srg"
        }
    }
}

sourceSets.main {
    resources {
        srcDir("src/main/generated")
        exclude("**/.cache/**")
    }
}
